'use client';
import { useState } from 'react';
import { Camera as CameraIcon, Edit3, Plus, Send, Users, Wifi, WifiOff } from 'lucide-react';
import { Camera, Caregiver, DemoData } from '@/lib/demo-data';
import Modal from './modal';
type Props = { data: DemoData; onChange: (data: DemoData) => void; notify: (message: string) => void };
export function Toggle({ checked, onChange, label }: { checked: boolean; onChange: () => void; label: string }) { return <button type="button" role="switch" aria-checked={checked} aria-label={label} className={`toggle ${checked ? 'on' : ''}`} onClick={onChange}><span/></button>; }
export function Cameras({ data, onChange, notify }: Props) {
  const [editing,setEditing] = useState<Camera | null>(null);
  function save(e: React.FormEvent<HTMLFormElement>) {
    e.preventDefault(); if (!editing) return;
    const camera = { ...editing, name: editing.name.trim(), location: editing.location.trim() };
    if (!camera.name || !camera.location) return;
    const exists = data.cameras.some(c => c.id === camera.id);
    onChange({ ...data, cameras: exists ? data.cameras.map(c => c.id===camera.id ? camera : c) : [...data.cameras,camera] });
    setEditing(null); notify(exists ? 'Đã cập nhật camera demo.' : 'Đã thêm camera demo. Chưa có kết nối camera thật.');
  }
  return <><div className="section-toolbar"><div><h2>{data.cameras.length} camera trong không gian</h2><p>Trạng thái kết nối và giám sát đều được mô phỏng.</p></div><button className="button" onClick={() => setEditing({ id: `CAM-${Date.now().toString().slice(-5)}`, name: '', location: '', online: true, enabled: true })}><Plus size={17}/> Thêm camera</button></div><div className="management-grid">{data.cameras.map(c => <section className="panel camera-card" key={c.id}><div className={`camera-preview ${!c.online || !c.enabled ? 'camera-inactive' : ''}`}><CameraIcon size={42}/><span>{c.id}</span><span className="preview-label">KHUNG CAMERA MÔ PHỎNG</span><div>{c.online && c.enabled ? <Wifi size={16}/> : <WifiOff size={16}/>} {!c.enabled ? 'Giám sát tạm dừng' : c.online ? 'Sẵn sàng giám sát' : 'Camera ngoại tuyến'}</div></div><div className="camera-info"><div><h3>{c.name}</h3><p>{c.location}</p></div><button className="icon-button" aria-label={`Sửa ${c.name}`} onClick={() => setEditing(c)}><Edit3 size={17}/></button></div><div className="camera-card-footer"><span>Bật giám sát</span><Toggle checked={c.enabled} label={`Giám sát ${c.name}`} onChange={() => { onChange({ ...data,cameras:data.cameras.map(x => x.id===c.id ? {...x,enabled:!x.enabled}:x) }); notify(c.enabled ? `Đã tạm dừng ${c.name}.` : `Đã bật giám sát ${c.name}.`); }}/></div></section>)}</div><p className="info-note">Khi tích hợp thật, mỗi camera sẽ có cấu hình RTSP và trạng thái do backend cập nhật. Bản demo chỉ lưu tên, vị trí và trạng thái thử nghiệm trên trình duyệt.</p>{editing && <Modal small title={data.cameras.some(c => c.id===editing.id) ? 'Chỉnh sửa camera' : 'Thêm camera demo'} onClose={() => setEditing(null)}><form className="modal-body form" onSubmit={save}><label>Tên camera<input required maxLength={60} value={editing.name} onChange={e => setEditing({...editing,name:e.target.value})} placeholder="Ví dụ: Camera phòng khách"/></label><label>Vị trí<input required maxLength={50} value={editing.location} onChange={e => setEditing({...editing,location:e.target.value})} placeholder="Ví dụ: Phòng khách"/></label><label className="checkbox-label"><input type="checkbox" checked={editing.online} onChange={e => setEditing({...editing,online:e.target.checked})}/> Mô phỏng camera đang kết nối</label><div className="form-actions"><button type="button" className="button" onClick={() => setEditing(null)}>Hủy</button><button type="submit" className="button primary" disabled={!editing.name.trim() || !editing.location.trim()}>Lưu camera</button></div></form></Modal>}</>;
}
export function Caregivers({ data, onChange, notify }: Props) {
  const [editing,setEditing] = useState<Caregiver | null>(null);
  function save(e: React.FormEvent<HTMLFormElement>) {
    e.preventDefault(); if (!editing) return;
    const person = {...editing,name:editing.name.trim(),relation:editing.relation.trim(),telegram:editing.telegram.trim()};
    if (!person.name || !person.relation || !person.telegram) return;
    const exists = data.caregivers.some(c => c.id===person.id);
    onChange({...data,caregivers:exists ? data.caregivers.map(c => c.id===person.id ? person : c) : [...data.caregivers,person]});
    setEditing(null);notify('Đã lưu người nhận cảnh báo demo.');
  }
  return <><div className="section-toolbar"><div><h2>{data.caregivers.length} người chăm sóc</h2><p>{data.caregivers.filter(c=>c.enabled).length} người đang bật nhận cảnh báo mô phỏng.</p></div><button className="button" onClick={() => setEditing({id:`CG-${Date.now()}`,name:'',relation:'',telegram:'',enabled:true})}><Plus size={17}/> Thêm người nhận</button></div><div className="caregiver-grid">{data.caregivers.map((p,i) => <section className="panel person-card" key={p.id}><div className="person-top"><div className={`person-avatar color-${i%3}`}>{p.name.split(' ').slice(-2).map(w=>w[0]).join('').toUpperCase()}</div><button className="icon-button" aria-label={`Sửa ${p.name}`} onClick={()=>setEditing(p)}><Edit3 size={17}/></button></div><h3>{p.name}</h3><p>{p.relation}</p><div className="telegram-handle"><Send size={16}/><span>{p.telegram}</span><small>Demo</small></div><div className="person-toggle"><div><strong>Nhận cảnh báo Telegram</strong><small>{p.enabled?'Đang bật':'Đã tắt'}</small></div><Toggle checked={p.enabled} label={`Nhận cảnh báo ${p.name}`} onChange={()=> { onChange({...data,caregivers:data.caregivers.map(c=>c.id===p.id?{...c,enabled:!c.enabled}:c)});notify('Đã cập nhật tùy chọn nhận cảnh báo demo.'); }}/></div></section>)}</div>{!data.caregivers.length && <div className="panel empty"><Users/><h3>Chưa có người nhận</h3><p>Thêm người chăm sóc để thử quy trình cảnh báo.</p></div>}<div className="info-note">Tên Telegram ở đây chỉ để minh họa. Khi tích hợp Telegram thật, người nhận cần bắt đầu cuộc trò chuyện với bot và backend lưu chat ID tương ứng.</div>{editing && <Modal small title="Thông tin người nhận cảnh báo" onClose={()=>setEditing(null)}><form className="modal-body form" onSubmit={save}><label>Họ và tên<input required maxLength={60} value={editing.name} onChange={e=>setEditing({...editing,name:e.target.value})}/></label><label>Vai trò / Quan hệ<input required maxLength={70} placeholder="Ví dụ: Con gái, người chăm sóc" value={editing.relation} onChange={e=>setEditing({...editing,relation:e.target.value})}/></label><label>Tên Telegram minh họa<input required maxLength={50} placeholder="@nguoinhan_demo" value={editing.telegram} onChange={e=>setEditing({...editing,telegram:e.target.value})}/></label><p className="muted">Chỉ nhập thông tin mẫu để trình bày.</p><div className="form-actions"><button className="button" type="button" onClick={()=>setEditing(null)}>Hủy</button><button className="button primary" type="submit" disabled={!editing.name.trim() || !editing.relation.trim() || !editing.telegram.trim()}>Lưu người nhận</button></div></form></Modal>}</>;
}
